apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-together
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-together
  template:
    metadata:
      labels:
        app: shop-together
    spec:
      containers:
      - name: shop-together
        image: your-registry/shop-together:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: shop-together-secrets
              key: mongodb-uri
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: shop-together-secrets
              key: shopify-api-key
        - name: SHOPIFY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: shop-together-secrets
              key: shopify-api-secret
        - name: SHOPIFY_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: shop-together-secrets
              key: shopify-access-token
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"